---
## Version-specific settings that override the values in cfg/config.yaml

node:
  components:
    - kubelet
    - proxy

  kubelet:
    cafile:
      - /root/cdk/ca.crt
    kubeconfig:
      - /root/cdk/kubeconfig
    confs:
      - /root/cdk/kubelet/config.yaml

  proxy:
    kubeconfig:
      - /root/cdk/kubeproxyconfig
